# Generated by Django 2.2.6 on 2019-11-07 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('reponsavel', models.CharField(max_length=100, verbose_name='Nome do Resposávek')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição do(s) serviço(s)')),
                ('documento', models.CharField(max_length=200, verbose_name='Documentos necessários')),
                ('bloco', models.CharField(max_length=50)),
                ('andar', models.CharField(max_length=30)),
                ('sala', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=30, verbose_name='horário de atendimento')),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Setor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
