# Generated by Django 2.2.6 on 2019-11-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=123456, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(default=1245, max_length=50, verbose_name='Função'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(default=9876452, max_length=15, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setor',
            name='andar',
            field=models.CharField(max_length=30, verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='bloco',
            field=models.CharField(max_length=50, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='sala',
            field=models.CharField(max_length=50, verbose_name='Sala'),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('documentos', models.CharField(max_length=250, verbose_name='Documentos')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['titulo'],
            },
        ),
    ]
