# Generated by Django 3.1.5 on 2021-01-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('reponsavel', models.CharField(max_length=100, verbose_name='Nome do Resposável')),
                ('localizacao', models.CharField(max_length=500, verbose_name='Localizacao(Link Maps)')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de serviço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('documentos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Documentos')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Titulo da diretoria')),
                ('responsavel', models.CharField(max_length=50, verbose_name='Responsavel')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'ordering': ['nome'],
            },
        ),
    ]
