# Generated by Django 3.1.5 on 2021-01-26 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Nome do Resposável')),
                ('localizacao', models.CharField(max_length=500, verbose_name='Localizacao(Link do Mapa da UFAC)')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('documentos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Documentos')),
                ('informacoes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mais informações(site UFAC)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['titulo'],
            },
        ),
    ]
