# Generated by Django 2.2.6 on 2019-11-18 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Titulo da diretoria')),
                ('responsavel', models.CharField(max_length=50, verbose_name='Responsavel')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.Setor')),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'ordering': ['nome'],
            },
        ),
    ]
