# Generated by Django 3.1.5 on 2021-01-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='andar',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='sala',
        ),
        migrations.AddField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(default='nada', max_length=500, verbose_name='Localizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setor',
            name='horario',
            field=models.CharField(max_length=30, verbose_name='Horário de atendimento'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='reponsavel',
            field=models.CharField(max_length=100, verbose_name='Nome do Resposável'),
        ),
    ]
