# Generated by Django 2.2.6 on 2019-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descroção'),
        ),
    ]
