# Generated by Django 3.1.5 on 2021-01-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_setor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='reponsavel',
            new_name='responsavel',
        ),
    ]
