# Generated by Django 2.2.6 on 2019-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_setor_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='documentos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='telefone',
            field=models.CharField(max_length=10, verbose_name='Telefone'),
        ),
    ]
