# Generated by Django 2.2.6 on 2019-10-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('reponsavel', models.CharField(max_length=100, verbose_name='Nome do Resposávek')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição do(s) serviço(s)')),
                ('documento', models.CharField(max_length=200, verbose_name='Documentos necessários')),
                ('bloco', models.CharField(max_length=50)),
                ('andar', models.CharField(max_length=30)),
                ('sala', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=30, verbose_name='horário de atendimento')),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
